### ISSUE TITLE
原工程好像启动不了了

### ISSUE THREAD

**Issue by ouliuquan** [ohmyide/theia-website-zh#2]
你好，我发起了一个PR，将原来的npm地址修改替换成yarnpkg，不做任何修改还是启动不了。
我也尝试了升级包再yarn、删除yarn.lock再yarn，各种组合尝试都失败了，你能帮忙看一下吗？

**Comment by ohmyide** [comment]
你的 PR 是修复的此问题？

**Comment by ouliuquan** [comment]
抱歉阿，不是，我的意思是我尝试了多种方法以后还是启动不了，我去原英文的工程([repo](https://github.com/eclipse-theia/theia-website))尝试了，也是报一样的错误代码，这不是你这边的问题。不好意思
